<?xml version="1.0" encoding="UTF-8"?>

<Project ToolsVersion="Current" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <PropertyGroup>
        <!-- The version used for all libraries in this project. -->
        <Version>0.1.0</Version>

        <TargetFramework>net481</TargetFramework>
        <LangVersion>preview</LangVersion>

        <DebugType>portable</DebugType>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

        <!-- Generate an XML documentation file so that others can see the doc comments -->
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <NoWarn>CS1591</NoWarn>

        <!-- Generate a nuget lockfile so that we can cache stuff in CI -->
        <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>

        <ProjectRootDir>$(MSBuildThisFileDirectory)</ProjectRootDir>

        <!-- Properties used by KSPBuildTools -->
        <GameDataSubDir>UnityExplorerMCP</GameDataSubDir>
        <GameDataOutDir>$(ProjectRootDir)\GameData\$(GameDataSubDir)</GameDataOutDir>
        <BinariesOutputRelativePath>GameData\$(GameDataSubDir)\Plugins</BinariesOutputRelativePath>
    </PropertyGroup>

    <!--
        Paths to GameData folders in the dependency set installs.
    -->
    <PropertyGroup>
        <DepSet1>$(ProjectRootDir)/deps/installs/depset1/GameData</DepSet1>
    </PropertyGroup>
</Project>
